#ifndef TEST_FLAGS_H
#define TEST_FLAGS_H

#define ENABLE_FSM_SIMULATION_TEST        0
#define ENABLE_RELAY_HARDWARE_TEST        0
#define ENABLE_FULL_SYSTEM_TEST           0
#define ENABLE_MQTT_CONFIGURATION_TEST    0

#define TEST_MODE_COUNT (ENABLE_FSM_SIMULATION_TEST + ENABLE_RELAY_HARDWARE_TEST + ENABLE_FULL_SYSTEM_TEST + ENABLE_MQTT_CONFIGURATION_TEST)

#if TEST_MODE_COUNT > 1
#error "Only one test mode may be enabled at a time."
#endif

#define TEST_MODE_ANY (TEST_MODE_COUNT > 0)

#endif
