[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1

framework = arduino

monitor_speed = 115200
upload_speed = 921600


lib_deps =
    adafruit/RTClib
    milesburton/DallasTemperature
    paulstoffregen/OneWire
    dfrobot/DFRobot_PH
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    knolleary/PubSubClient      ; MQTT client
    bblanchon/ArduinoJson       ; JSON serializer